export const KEYS = {
  SCHEMA_OPTIONS: Symbol('SCHEMA_OPTIONS'),
  SCHEMA_DEFINITION: Symbol('SCHEMA_DEFINITION'),
  SCHEMA_INDEXES: Symbol('SCHEMA_INDEXES'),
  SCHEMA_CASCADE: Symbol('SCHEMA_CASCADE'),

  REPOSITORY_BEFORE: Symbol('REPOSITORY_BEFORE'),
  REPOSITORY_AFTER: Symbol('REPOSITORY_AFTER'),
  REPOSITORY_ACTIONS: Symbol('REPOSITORY_ACTIONS'),
}
